version: 4.0.0.{build}

skip_commits:
  files:
    - docs/*
    - '**/*.md'

image: Visual Studio 2013

nuget:
  account_feed: true
  project_feed: true

configuration: Release

skip_tags: true

build:
  project: ES1PowerShell.sln
  parallel: false
  verbosity: minimal

artifacts:
  - path: Release\en-us\ES1PowerShellInstall.msi
    name: ES1POSHInstaller

deploy:  
  - provider: FTP
    protocol: ftp
    host: ftp.emc.com
    username: rosenj4
    password: B4QLQDAoII
    artifact: ES1POSHInstaller
    folder: SourceOne PowerShell
  
  - provider: GitHub
    tag: v$(appveyor_build_version)
    release: EMC SourceOne PowerShell v$(appveyor_build_version)
    artifact: ES1POSHInstaller  
    auth_token:
     secure: eM9AE60GLNzpltXgt+FT8ur+h89SjtWRaJPPClF2h2ztYarbzcvj8rk1wY7kvpJ8
    draft: false
    prerelease: true
    on:
      branch: master                # release from master branch only
      appveyor_repo_tag: false       # deploy on tag push only
 
on_success:
  - git config --global credential.helper store
  - ps: Add-Content "$HOME\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "jrosenth@comcast.net"
  - git config --global user.name "Jay R."
  - git checkout master
  - git commit SourceOne_POSH\SourceOne_POSH.psd1 -m "AppVeyor Build [skip ci]"
  - git push origin master
  
environment:
  access_token:
    secure: eM9AE60GLNzpltXgt+FT8ur+h89SjtWRaJPPClF2h2ztYarbzcvj8rk1wY7kvpJ8
    
