version: 4.0.0.{build}

skip_commits:
  files:
    - docs/*
    - '**/*.md'

image: Visual Studio 2013

nuget:
  account_feed: true
  project_feed: true

configuration: Release

build:
  project: ES1PowerShell.sln
  parallel: false
  verbosity: minimal

artifacts:
  - path: Release\en-us\ES1PowerShellInstall.msi

on_success:
  - git commit SourceOne_POSH\SourceOne_POSH.psd1
  - git push
