version: 4.0.0.{build}

image: Visual Studio 2013

nuget:
  account_feed: true
  project_feed: true

platform:
  - x86
  - Any CPU

configuration: Release

build:
  project: ES1PowerShell.sln
  parallel: false
  verbosity: minimal
  
